name: Release KCM
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
  test:
    needs: gosec
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
  release:
    needs: [gosec, test]
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/master'
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v3
        with:
          registry: ghcr.io
          username: "EladLeev"
          password: ${{ secrets.GHCR_TOKEN }}
          repository: eladleev/kafka-config-metrics
          tags: latest